events { 
    worker_connections 1024; 
}

http {
    upstream backend_cluster {
        # Definimos los servidores por su nombre (Render maneja internamente el puerto 443)
        server clouddash-backend-1.onrender.com:443;
        server clouddash-backend-2.onrender.com:443;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass https://backend_cluster;
            
            # Líneas críticas para solucionar el error de SSL Handshake en Render:
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
            
            # Forzamos que la cabecera Host cambie dinámicamente según el backend activo
            proxy_set_header Host $proxy_host;
            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}